### ISSUE TITLE
Docker image still using old MMDC version 8.4.8

### ISSUE THREAD

**Issue by Marloxo** [neenjaw/compile-mermaid-markdown-action#13]
Hey again!

seems the new docker image `neenjaw/mermaid:8.7.0`, is still using the old node module `MMDC version 8.4.8` 

<img width="438" alt="Screenshot 2020-08-26 at 3 45 05 PM" src="https://user-images.githubusercontent.com/5578831/91275731-1ecaf080-e7b3-11ea-931d-ba0e6f12dd3c.png">

**Comment by Marloxo** [comment]
I'm guessing when the docker image built, it was using cache instead of downloading the dependency once again


if this is the case then we will need to do, `docker build --no-cache -t <docker_tag> .`

<img width="418" alt="Screenshot 2020-08-26 at 4 01 31 PM" src="https://user-images.githubusercontent.com/5578831/91277659-b6314300-e7b5-11ea-8a9f-e811fb75f82c.png">

**Comment by neenjaw** [comment]
Hmm. That's weird. I had built it once locally to test and it had worked, so then did a rebuild and push. Yes, I'll work on this tonight. Sorry for the hassle.

**Comment by neenjaw** [comment]
Okay. I found the problem.  Because gha doesn't cache the docker image used by the action, I build a higher level image thatwould be cached every time.  mmdc is pulled in at that stage.

I can fix this fast.

Again, sorry for the hassle.

**Comment by neenjaw** [comment]
```shell
root@dfa658bcd1b2:/# ./node_modules/.bin/mmdc -V
8.7.0
```

Updated now. re-psuhing image

**Comment by neenjaw** [comment]
It should be updated now

**Comment by neenjaw** [comment]
https://hub.docker.com/layers/neenjaw/mermaid/8.7.0/images/sha256-f40f9beedf869669caed379db096e9003b75b9e6196424287cf7cce00867fe99?context=explore

**Comment by neenjaw** [comment]
Let me know if this works for you. I will resolve the issue if it does.

**Comment by omar-binary** [comment]
hey @neenjaw sorry wasn't around, thank you so much for the update, it's working fine now 🎉

**Comment by Marloxo** [comment]
hey @neenjaw sorry wasn't around, thank you so much for the update, it's working fine now 🎉
