### ISSUE TITLE
puppeteer, Error: Failed to launch the browser process!

### ISSUE THREAD

**Issue by Marloxo** [neenjaw/compile-mermaid-markdown-action#14]
Hi again!
I found my self keep jumping back here, with new stories every time 😹 

 So seems there is some changes in puppeteer, I haven't figure out exactly what is the reason, but when I try to do change in my markdown to generate new image, I'm getting this error.

![Screenshot 2020-09-01 at 1 57 34 PM](https://user-images.githubusercontent.com/5578831/91800396-79ed5f00-ec5b-11ea-8ce0-838fbbb0b282.png)

ref: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

**Comment by neenjaw** [comment]
Does it do it when compiling all images or just images with the new features? I had it compiling the basic diagram to an image that is in the example markdown.

**Comment by Marloxo** [comment]
I just test it on the example markdown, it show the same error

**Comment by neenjaw** [comment]
Hmm. Let me think on this.

**Comment by Marloxo** [comment]
So I tried to SSH into the docker image and install the missing lib using:

```
apt-get install libxss1 -y
```

Now when I run the following command on the example markdown:

```
/node_modules/.bin/mmdc -i /test/test.md -o /test/test.png
```

I'm getting this error:

![Screenshot 2020-09-01 at 3 03 33 PM](https://user-images.githubusercontent.com/5578831/91812840-567ae200-ec64-11ea-8778-f618570b341b.png)

**Comment by Marloxo** [comment]
my bad, the last error bcz I missed passing `-p puppeteer-config.json` option when run the command,

I guess that mean, it's only need, ```apt-get install libxss1 -y``` in docker image in order to run

**Comment by neenjaw** [comment]
So it works with that library installed?

**Comment by Marloxo** [comment]
yes, all it need is to update docker image with this library installed

**Comment by neenjaw** [comment]
Very strange, maybe I had inadvertently updated it when I was testing rather than before. Will do that in the next day. 

Thanks for troubleshooting this.

**Comment by neenjaw** [comment]
I'm pushing a new image now

**Comment by neenjaw** [comment]
It again, seems to work for me, but if you can verify, that would be great

**Comment by omar-binary** [comment]
yup, it's working fine for me now! thanks 🎉

**Comment by Marloxo** [comment]
yup, it's working fine for me now! thanks 🎉
