### ISSUE TITLE
Compile inline

### ISSUE THREAD

**Issue by abergmeier** [neenjaw/compile-mermaid-markdown-action#17]
I am a user of [Markdown Preview in VSCode](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-mermaid&ssr=false#overview). When it comes to Mermaid compilation I would like to have the same functionality. Namely, inline "replacement" of Mermaid diagrams to a new file.

I would imagine this to work like this:

```mermaid
flowchart
  MM(.md.mermaid)
  A[Action]
  CB>Mermaid Codeblock]
  MMCLI[Mermaid CLI]
  MD(.md)
  
  A -- 1. reads --> MM
  A -- 2. searches --> CB
  A -. 3. delegates compile .-> MMCLI
  MMCLI <-- 4. compiles --> CB
  A -- 5. writes with inlined --> MD
```

So perhaps this could be done by 2 settings:
1. `stripPathSuffix` in yaml which you could set to `.mermaid` in this case. This would then generate output in a new file.
2. New Env `REMOVE_CODEBLOCKS`, which you know removes the codeblocks.

**Comment by neenjaw** [comment]
I'm busy with some other projects right now, but I'm happy to review and incorporate a PR if you'd like to do that.

1. probably is just a change to the workflow and shell script

2. requires adding the flag to the workflow, shell script and the awk script

This is probably best done in two PR's.
