### ISSUE TITLE
Update to 8.9.x?

### ISSUE THREAD

**Issue by disambiguationuk** [neenjaw/compile-mermaid-markdown-action#28]
Hey, nice work on the action. Making good use of it. Just wondering if you could update to 8.9? I kept getting compile errors and had to downgrade my markdown back to 8.7 which loses a few things. There's also not a nice version checker on the Mermaid-js API docs so all of the guidance is for 8.9.2 so it's a lot of trial and error to figure out what syntax isn't supported in 8.7.

**Comment by neenjaw** [comment]
Hey, thanks for creating an issue! I'll try to take a look at this over the weekend.

**Comment by neenjaw** [comment]
I think I've bumped the image to 8.9.2 now.  Update your action version to: https://github.com/neenjaw/compile-mermaid-markdown-action/releases/tag/0.3.0

**Comment by neenjaw** [comment]
Let me know if it works for you, if it does I'll mark this as closed.

**Comment by disambiguationuk** [comment]
Nice one, that looks like it's all working cheers! Had another request but I think I might have a go at doing a PR for that one

**Comment by neenjaw** [comment]
Sounds good, I'm open to PRs to expand functionality if they can be generalized with reasonable default options for basic usage. Might be best to open an issue to discuss before doing a tonne of work
