### ISSUE TITLE
SVG Support

### ISSUE THREAD

**Issue by disambiguationuk** [neenjaw/compile-mermaid-markdown-action#29]
Hey, opening a new issue at your suggestion @neenjaw. As I've said, loving this action, we're beginning to integrate it across our documentation. I'm looking to see if we can get SVG support instead of just PNGs. Now GitHub supports it's own dark mode and with people using various dark theme plugins the current implementation with only PNGs doesn't resolve too well across both, SVGs might solve much of this.

I'm pretty sure Mermaid should do this as their Live Editor supports it.

As I said in the other one I'm happy to do a little work to try to get this working, willing to give it a go. Looking to use an env argument similar to your HIDE_CODEBLOCKS and ABSOLUTE_IMAGE_LINKS switches. Default behaviour would be to use PNGs.

**Comment by neenjaw** [comment]
Sounds like a pretty reasonable addition that, depending how the mermaid cli works, could be as easy as setting a flag. 

I like the idea of svg for scaling/resizing issues as well

**Comment by disambiguationuk** [comment]
Cool, I'd like to give it a go myself as I've never really contributed to public projects before. Be interesting to have a try?

**Comment by neenjaw** [comment]
Cool, ya, just fork and submit a PR whenever. If you have questions, just ask and I'll see how I can help. :D

**Comment by disambiguationuk** [comment]
Nice, I don't really know shell (yet) but I'm just adapting your existing entrypoint.sh to pass through an out_file_type through to everywhere with .png. At the risk of sounding extremely dense... how do I build/test local?

**Comment by neenjaw** [comment]
> Nice, I don't really know shell (yet) but I'm just adapting your existing entrypoint.sh to pass through an out_file_type through to everywhere with .png.

Yea, the pattern used so far is that it reads the ENV variable, if it exists the we set the value, if not we use the default 

```bash
# can do this in one line in bash:
output_file_type="${OUTPUT_FILE_TYPE:-png}"
```

> At the risk of sounding extremely dense... how do I build/test local?

If you have the mermaid cli working locally, you should just be able to run the entrypoint.sh script but pass in the env variables yourself.

If you want to run it through the workflow, you probably need to set up a test repo that uses your forked workflow. I have another repo `mermaid-markdown-test` which I've used for this.

**Comment by disambiguationuk** [comment]
Ah yeah that's a better idea than just following the binary pattern as it looks like mermaid CLI also supports pdf too (and with SVG supports a few additional things). So default behaviour as "png" and then overridden by "svg" and "pdf", worth doing an upfront check on the filetype matching png, svg or pdf do you think or just pass it straight through regardless of what string the user specifies?

**Comment by disambiguationuk** [comment]
Yes mate SVG! https://github.com/disambiguationuk/MermaidTest/blob/master/docs/assets/docs_mermaid-md-1.svg

**Comment by neenjaw** [comment]
> Ah yeah that's a better idea than just following the binary pattern as it looks like mermaid CLI also supports pdf too (and with SVG supports a few additional things). So default behaviour as "png" and then overridden by "svg" and "pdf", worth doing an upfront check on the filetype matching png, svg or pdf do you think or just pass it straight through regardless of what string the user specifies?

Your choice depending on what you want to do. This is a tool, and sometimes tools are sharp. If mermaid cli requires a specific string capitalization though, it might be nice to throw an error and notify a user though.

**Comment by disambiguationuk** [comment]
Hmm yeah worth checking if your function cascades an invalid filetype back in a verbose manner. And also worth doing a "ToLower ()" equivalent to the output_file_type too, if only for cleaner output. I'll take a look and add them to the PR.

**Comment by neenjaw** [comment]
I merged it as it is, I think it could be worthwhile adding those small check to make the developer experience better but that can be added in a followup PR.  My suggestion would be to make a bash function which can be called near the bottom of `entrypoint.sh` where there is other code similar to that.

**Comment by disambiguationuk** [comment]
Yeah good idea, I'll take a look at that later on.
