### ISSUE TITLE
Update mermaid version

### ISSUE THREAD

**Issue by fdaguin** [neenjaw/compile-mermaid-markdown-action#37]
Hi, 

thanks a lot for this project! Could you please update Mermaid to its latest version?

At the moment, there is no way for us to contribute for updating this CLI because the Docker image build process is handled manually. I see in #6 that caching was an issue. Were you aware of [actions/cache](https://github.com/actions/cache)?

Thanks!

**Comment by neenjaw** [comment]
I am, it wasn't really a thing when I developed this project I think. Would be interested in moving it over to actions cache, but I don't really have a lot of time for this project to work on it at the moment.
