### ISSUE TITLE
Please update CLI - GitHub Mermaid support doesn’t cover GH Pages 

### ISSUE THREAD

**Issue by snomos** [neenjaw/compile-mermaid-markdown-action#41]
Thanks for a great GH Action. Now that GitHub has released their Mermaid support, it seems it doesn’t cover GH Pages. That is, Mermaid graphics will render fine in README’s, source views of md files, in issues etc, but they will _not_ render in GitHub Pages. 

This means that your Action is still very much needed.

I would very much like to be proven wrong, but it doesn’t seem likely.

Please update the CLI to the newest version.

**Comment by neenjaw** [comment]
Hey @snomos,

I'm glad you've found value in this action.  I just don't have the time to maintain this project anymore.  Like I've noted in other issues, my intention is to archive this project now that mermaid is supported in most cases.  I understand it does not work for markdown files in the context of github pages usage.

As you likely know (but for others searching later), you can use mermaid diagrams in an html page like so:

```html
<html>
    <body>
        <h1>Mermaid Test</h1>

        <div class="mermaid">
            graph TD
                A[Client] --> B[Load Balancer] 
                B --> C[Server01] 
                B --> D[Server02]
        </div

    </body>
    <script src="https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js"></script>
</html>
```

Feel free to fork this project.  To update the image, you can use [this dockerfile](https://hub.docker.com/r/neenjaw/mermaid) here to re-create the image, push it do your dockerhub and then use it in the action's Dockerfile
