### ISSUE TITLE
Dockerfile source code?

### ISSUE THREAD

**Issue by rafaeldelboni** [neenjaw/compile-mermaid-markdown-action#6]
Hello, I hope you doing well thanks for your work on this repo!

Could you please share with us the `neenjaw/mermaid:node-13` Dockerfile source code? 

Would be easy to update mermaid versions and make some forks of this repo :)

**Comment by neenjaw** [comment]
https://hub.docker.com/repository/docker/neenjaw/mermaid/general

**Comment by neenjaw** [comment]
The source docker information is in the dockerhub link, it is built and tagged there because then github actions will cache the image.  For images built in the action, the steps are not cached and the image takes quite a while to build with the download of chrome, etc.
