### ISSUE TITLE
The examples are using neenjaw as the assignees/reviewers instead of ${{ github.actor }}

### ISSUE THREAD

**Issue by mvoncken** [neenjaw/compile-mermaid-markdown-action#7]
A copy and paste of the examples would be easier if the examples used the repo owner, see title.

**Comment by neenjaw** [comment]
Nice! I probably don't have time to get to this in the next few days, if you PR it and I can merge the change. :smile:

**Comment by Marloxo** [comment]
this PR should address this issue

https://github.com/neenjaw/compile-mermaid-markdown-action/pull/12

**Comment by neenjaw** [comment]
Wonderful, it has been merged!
