### ISSUE TITLE
ABSOLUTE_IMAGE_LINKS: 0/1 is missing in the examples in the README

### ISSUE THREAD

**Issue by mvoncken** [neenjaw/compile-mermaid-markdown-action#8]
please set a default for ABSOLUTE_IMAGE_LINKS in the examples. 
ommitting ABSOLUTE_IMAGE_LINKS from the env will make the action fail.

or make the action work when ABSOLUTE_IMAGE_LINKS is not provided.

**Comment by mvoncken** [comment]
p.s. outside of the env and actor issue in the example this works great, Thanks!

**Comment by neenjaw** [comment]
Nice! I probably don't have time to get to this in the next few days, if you PR it and I can merge the change. :smile:

**Comment by omar-binary** [comment]
If this still open, I can pick it up, sending PR with my personal account

**Comment by neenjaw** [comment]
As far as I know, please do!

**Comment by Marloxo** [comment]
@neenjaw  I really like what you did with this project, and I guess I'm interested to pick-up some tasks here to help

could you please check, if it's good to merge xD

https://github.com/neenjaw/compile-mermaid-markdown-action/pull/12

**Comment by neenjaw** [comment]
Thanks, it was really neat to make this little project.  I'm not using it actively at the moment, but I am glad that others are finding it useful.

Thanks for your PR's, I really appreciate it.
