### ISSUE TITLE
Update cli source

### ISSUE THREAD

**Issue by omar-binary** [neenjaw/compile-mermaid-markdown-action#9]
there are some breaking changes in mermaid-cli with a lot of new features, I would propose to update the current version,

I'm sending a PR for it

**Comment by omar-binary** [comment]
I appreciate if you can review when you got time

https://github.com/neenjaw/compile-mermaid-markdown-action/pull/11

**Comment by neenjaw** [comment]
Reviewed and merged! Thanks much!
